---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
requires:
  - configs: ["app"]
---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: ghcr.io/kzmake/examples/basic-service-invocation-py/api-gateway
      docker: { dockerfile: Dockerfile.golang, network: host, buildArgs: { SERVICE_NAME: api/gateway } }
    - image: ghcr.io/kzmake/examples/basic-service-invocation-py/svc-user
      docker: { dockerfile: Dockerfile.python, network: host, buildArgs: { SERVICE_NAME: svc/user } }
    - image: ghcr.io/kzmake/examples/basic-service-invocation-py/svc-blog
      docker: { dockerfile: Dockerfile.python, network: host, buildArgs: { SERVICE_NAME: svc/blog } }
    - image: ghcr.io/kzmake/examples/basic-service-invocation-py/svc-email
      docker: { dockerfile: Dockerfile.python, network: host, buildArgs: { SERVICE_NAME: svc/email } }
    - image: ghcr.io/kzmake/examples/basic-service-invocation-py/svc-wallet
      docker: { dockerfile: Dockerfile.python, network: host, buildArgs: { SERVICE_NAME: svc/wallet } }
deploy:
  kustomize:
    paths:
      - manifests/overlays/localhost
portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: default
    port: 8080
    localPort: 58080
  - resourceType: service
    resourceName: svc-user
    namespace: default
    port: 5050
    localPort: 55050
profiles:
  - name: localhost
  - name: production
    deploy:
      kustomize:
        paths:
          - manifests/overlays/production
