---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-hoge
spec:
  selector:
    matchLabels:
      app: svc-hoge
  template:
    metadata:
      labels:
        app: svc-hoge
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "svc-hoge"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "5050"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "error"
        dapr.io/config: "common-dapr-config"
    spec:
      containers:
        - name: svc-hoge
          image: kzmake/svc-hoge:latest
          command:
            - /app
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: svc-hoge-config
              prefix: HOGE_
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 32Mi
          ports:
            - name: grpc
              containerPort: 5050
          livenessProbe:
            tcpSocket: { port: 5050 }
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket: { port: 5050 }
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: svc-hoge
spec:
  type: ClusterIP
  selector:
    app: svc-hoge
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: svc-hoge-config
data:
  ADDRESS: 0.0.0.0:5050
  DAPR_ADDRESS: localhost:50001
